steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/election-frontend'
      - '.'
images:
  - 'gcr.io/${PROJECT_ID}/election-frontend'
substitutions:
  _VITE_API_URL: 'https://election-backend-813017487356.us-central1.run.app/api'
